### ISSUE TITLE
how the complete tree form in random forest demo_local,py

### ISSUE THREAD

**Issue by monuheeya** [cyqclark/fedlearn-algo#25]
0: {0: {'processed': True}, 1: {'processed': True}, 2: {'processed': True}, 3: {'processed': True, 'is_leaf': True}, 4: {'processed': True}, 5: {'processed': True, 'is_leaf': True}, 6: {'processed': True}, 9: {'processed': True, 'is_leaf': True}, 10: {'processed': True}, 13: {'processed': True, 'is_leaf': True}, 14: {'processed': True}, 21: {'processed': True, 'is_leaf': True}, 22: {'processed': True, 'is_leaf': True}, 29: {'processed': True, 'is_leaf': True}, 30: {'processed': True, 'is_leaf': True}}}
 how with this information we can analyse  the tree,which one is root which one is leaf

**Comment by guabao** [comment]
Hi,

The context you provide is limited but let me try to answer it.

I suppose you are asking the debug information in the federated random forest code. The debug information in the code is a collection of flags showing if a node is processed and if a node is a leaf. It is a dictionary with tree id (start from zero) as keys and tree information as values. The tree information is a sub-dictionary with tree node id (start from zero) as keys and node information as values. Therefore, "0" node is the the root of each tree, and the nodes with {'is_leaf': True} are the leaves of the tree.

More contexts are welcome.

Jiazhou

**Comment by monuheeya** [comment]
Thank you for your response that part i have understood, I am asking about 
1.what is the meaning of features here(how these value come from which part)
2.root value is features value or something else
3.how we can interpret from client forest  which one is child and which one is parent
4. what is the use of percentiles

**Comment by guabao** [comment]
The information you provided does not contain any decision information. It is flag information to record which node is processed and which is not.

Here is part of my answers for your specific questions:
1. I am not quite sure about "features" you mentioned, can you point it out in the source code or write down a piece of code to show the variable you want to get?
2. Again, I am not sure about the "root value" you mentioned here.
3. There are several ways to do this, here is one of them: if the tree is centralized (the demo code uses this mode), then the information of root or children can be found in the active client which has labels for the training task.
4. I assume you are asking about the "percentiles" in the parameters part. This parameter controls the number of glued statistics (sum or mean) calculated during the process of finding the optimal split points. For example, if the nubmer of percentiles is two, then for each node the algorithm will separate the sample in two bins and calculate the statistics in each bin. This process leads a decision whether 50% percentile is a good split points or not.

Unfortunately, I am not able to answer all of your questions due to the limited information. More details are welcome.

Jiazhou
